import { DetectedEnvVar, EnvVarType } from '@/types';

/**
 * Typed Accessor Generator
 * Generates a TypeScript env.ts file with Zod validation.
 */
export class AccessorGenerator {
  /**
   * Generate a complete env.ts file with typed accessors.
   */
  generate(variables: DetectedEnvVar[], projectName?: string): string {
    const lines: string[] = [
      '/**',
      ` * ${projectName || 'Project'} — Environment Variables`,
      ' * Auto-generated by EnvDoctor',
      ` * Generated at: ${new Date().toISOString()}`,
      ' */',
      '',
      "import { z } from 'zod';",
      '',
      '// ─── Schema Definition ───────────────────────────────────────',
      '',
    ];

    // Build schema
    lines.push('const envSchema = z.object({');
    for (const v of variables) {
      lines.push(`  ${this.formatSchemaEntry(v)}`);
    }
    lines.push('});', '', '');

    // Type export
    lines.push(
      '// ─── Inferred Type ───────────────────────────────────────────',
      '',
      'export type Env = z.infer<typeof envSchema>;',
      '',
      '// ─── Validated Accessor ──────────────────────────────────────',
      '',
      'const parsed = envSchema.safeParse(process.env);',
      '',
      'if (!parsed.success) {',
      "  console.error('❌ Invalid environment variables:');",
      '  console.error(JSON.stringify(parsed.error.flatten(), null, 2));',
      "  throw new Error('Invalid environment variables. Check your .env file.');",
      '}',
      '',
      'export const env = parsed.data;',
      '',

      '// ─── Individual Accessors ────────────────────────────────────',
      '',
    ];

    for (const v of variables) {
      const accessorName = this.toCamelCase(v.name);
      lines.push(`/** ${v.description || v.name} */`);
      lines.push(`export const ${accessorName} = env.${accessorName};`);
      lines.push('');
    }

    // Helper to check if env var exists
    lines.push(
      '// ─── Helpers ─────────────────────────────────────────────────',
      '',
      '/** Check if an environment variable is set. */',
      'export function hasEnvVar(name: string): boolean {',
      '  return name in process.env && process.env[name] !== undefined;',
      '}',
      '',
      '/** Get a raw environment variable (without validation). */',
      'export function getRawEnvVar(name: string, fallback?: string): string | undefined {',
      '  return process.env[name] ?? fallback;',
      '}',
      '',

      'export default env;',
    );

    return lines.join('\n');
  }

  /**
   * Format a single Zod schema entry.
   */
  private formatSchemaEntry(v: DetectedEnvVar): string {
    const key = this.toCamelCase(v.name);
    let zodType: string;

    switch (v.type) {
      case 'number':
        zodType = 'z.coerce.number()';
        break;
      case 'boolean':
        zodType = 'z.coerce.boolean()';
        break;
      case 'url':
        zodType = 'z.string().url()';
        break;
      case 'json':
        zodType = 'z.string().transform((v) => JSON.parse(v))';
        break;
      default:
        zodType = 'z.string()';
    }

    // Add default if available
    if (v.defaultValue !== undefined && v.defaultValue !== '') {
      if (v.type === 'number') {
        zodType += `.default(${v.defaultValue})`;
      } else if (v.type === 'boolean') {
        zodType += `.default(${v.defaultValue === 'true' ? 'true' : 'false'})`;
      } else {
        zodType += `.default('${v.defaultValue}')`;
      }
    } else if (v.required) {
      // Keep as required (no .optional())
    } else {
      zodType += '.optional()';
    }

    // Map env var name
    return `${key}: ${zodType}, // ${v.name}${v.isSecret ? ' 🔒' : ''}`;
  }

  /**
   * Convert SCREAMING_SNAKE_CASE to camelCase.
   */
  private toCamelCase(name: string): string {
    return name
      .toLowerCase()
      .replace(/_([a-z])/g, (_, char) => char.toUpperCase());
  }
}

export const accessorGenerator = new AccessorGenerator();
