import { DetectedEnvVar, ScanResult } from '@/types';

/**
 * Documentation Generator
 * Produces Markdown documentation from scan results.
 */
export class DocGenerator {
  /**
   * Generate a full Markdown documentation file.
   */
  generateMarkdown(scan: ScanResult): string {
    const lines: string[] = [
      '# Environment Variables',
      '',
      `> Auto-generated by EnvDoctor on ${new Date().toISOString()}`,
      '',
      `**Project:** ${scan.projectId || 'Unknown'}`,
      `**Files scanned:** ${scan.stats.totalFiles}`,
      `**Variables found:** ${scan.stats.totalVariables}`,
      `**Secrets detected:** ${scan.stats.secretsDetected}`,
      '',
      '---',
      '',
    ];

    // Summary table
    lines.push('## Summary', '');
    lines.push('| Variable | Type | Required | Default | Secret | Description |');
    lines.push('|----------|------|----------|---------|--------|-------------|');

    for (const v of scan.variables) {
      lines.push(this.formatTableRow(v));
    }

    lines.push('', '---', '');

    // Detailed sections
    lines.push('## Details', '');

    const secrets = scan.variables.filter((v) => v.isSecret);
    const required = scan.variables.filter((v) => v.required && !v.isSecret);
    const optional = scan.variables.filter((v) => !v.required && !v.isSecret);

    if (secrets.length > 0) {
      lines.push('### 🔐 Secrets', '');
      for (const v of secrets) {
        lines.push(this.formatDetail(v));
      }
    }

    if (required.length > 0) {
      lines.push('### ✅ Required Variables', '');
      for (const v of required) {
        lines.push(this.formatDetail(v));
      }
    }

    if (optional.length > 0) {
      lines.push('### ⚙️ Optional Variables', '');
      for (const v of optional) {
        lines.push(this.formatDetail(v));
      }
    }

    // Files scanned
    lines.push('---', '', '## Files Scanned', '');
    for (const f of scan.files) {
      lines.push(`- \`${f.path}\` (${f.language}, ${f.envVarCount} variables)`);
    }

    // Stats
    lines.push('', '---', '', '## Statistics', '');
    lines.push(`- **Total files:** ${scan.stats.totalFiles}`);
    lines.push(`- **Total variables:** ${scan.stats.totalVariables}`);
    lines.push(`- **Secrets detected:** ${scan.stats.secretsDetected}`);

    if (Object.keys(scan.stats.byType).length > 0) {
      lines.push('', '### By Type', '');
      for (const [type, count] of Object.entries(scan.stats.byType)) {
        lines.push(`- ${type}: ${count}`);
      }
    }

    if (Object.keys(scan.stats.byLanguage).length > 0) {
      lines.push('', '### By Language', '');
      for (const [lang, count] of Object.entries(scan.stats.byLanguage)) {
        lines.push(`- ${lang}: ${count}`);
      }
    }

    return lines.join('\n');
  }

  private formatTableRow(v: DetectedEnvVar): string {
    const def = v.defaultValue ? `\`${v.defaultValue}\`` : '—';
    const desc = v.description ? v.description.replace(/\|/g, '\\|') : '—';
    return `| \`${v.name}\` | ${v.type} | ${v.required ? '✅ Yes' : '❌ No'} | ${def} | ${v.isSecret ? '🔒 Yes' : 'No'} | ${desc} |`;
  }

  private formatDetail(v: DetectedEnvVar): string {
    const lines: string[] = [
      `#### \`${v.name}\``,
      '',
      `- **Type:** ${v.type}`,
      `- **Required:** ${v.required ? 'Yes' : 'No'}`,
    ];

    if (v.defaultValue) {
      lines.push(`- **Default:** \`${v.defaultValue}\``);
    }

    if (v.description) {
      lines.push(`- **Description:** ${v.description}`);
    }

    lines.push(`- **Secret:** ${v.isSecret ? '🔒 Yes' : 'No'}`);
    lines.push(`- **Usage count:** ${v.usageCount}`);
    lines.push(`- **Files:** ${v.files.map((f) => `\`${f}\``).join(', ')}`);

    if (v.usagePatterns.length > 0) {
      lines.push('- **Usage patterns:**');
      for (const p of v.usagePatterns) {
        lines.push(`  - \`${p}\``);
      }
    }

    lines.push('');
    return lines.join('\n');
  }

  /**
   * Generate JSON output.
   */
  generateJSON(scan: ScanResult): string {
    return JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        projectId: scan.projectId,
        stats: scan.stats,
        variables: scan.variables,
        files: scan.files,
      },
      null,
      2,
    );
  }

  /**
   * Generate .env.example file.
   */
  generateEnvExample(variables: DetectedEnvVar[]): string {
    const lines: string[] = ['# .env.example — generated by EnvDoctor', ''];

    const required = variables.filter((v) => v.required);
    const optional = variables.filter((v) => !v.required);

    if (required.length > 0) {
      lines.push('# === Required ===');
      for (const v of required) {
        if (v.description) lines.push(`# ${v.description}`);
        if (v.isSecret) lines.push('# ⚠️ This is a secret — do not commit the real value');
        lines.push(`${v.name}=`);
        lines.push('');
      }
    }

    if (optional.length > 0) {
      lines.push('# === Optional ===');
      for (const v of optional) {
        if (v.description) lines.push(`# ${v.description}`);
        lines.push(`${v.name}=${v.defaultValue || ''}`);
        lines.push('');
      }
    }

    return lines.join('\n');
  }
}

export const docGenerator = new DocGenerator();
