import { DriftResult } from '@/types';

/**
 * Drift Detection Engine
 * Compares .env.example against actual environment variable usage.
 */
export class DriftDetector {
  /**
   * Compare expected env vars (from .env.example) with detected vars (from scan).
   */
  detect(
    expectedVars: string[],
    detectedVars: string[],
  ): DriftResult {
    const expectedSet = new Set(expectedVars.map((v) => v.toUpperCase()));
    const detectedSet = new Set(detectedVars.map((v) => v.toUpperCase()));

    const missingVars = detectedVars.filter((v) => !expectedSet.has(v.toUpperCase()));
    const extraVars = expectedVars.filter((v) => !detectedSet.has(v.toUpperCase()));
    const matchedVars = detectedVars.filter((v) => expectedSet.has(v.toUpperCase()));

    return {
      missingVars: [...new Set(missingVars)],
      extraVars: [...new Set(extraVars)],
      matchedVars: [...new Set(matchedVars)],
    };
  }

  /**
   * Parse .env.example file content into variable names.
   */
  parseEnvExample(content: string): string[] {
    const vars: string[] = [];
    const lines = content.split('\n');

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines and comments
      if (!trimmed || trimmed.startsWith('#')) continue;

      // Extract variable name (before = or :)
      const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)\s*[=:]/i);
      if (match) {
        vars.push(match[1]);
      }
    }

    return vars;
  }

  /**
   * Generate a drift report summary.
   */
  generateSummary(drift: DriftResult): {
    status: 'healthy' | 'warning' | 'critical';
    message: string;
    details: string[];
  } {
    const details: string[] = [];
    let status: 'healthy' | 'warning' | 'critical' = 'healthy';

    if (drift.missingVars.length > 0) {
      details.push(`${drift.missingVars.length} variable(s) used in code but missing from .env.example: ${drift.missingVars.join(', ')}`);
      status = 'warning';
    }

    if (drift.extraVars.length > 0) {
      details.push(`${drift.extraVars.length} variable(s) in .env.example but not used in code: ${drift.extraVars.join(', ')}`);
      status = status === 'warning' ? 'warning' : 'warning';
    }

    if (drift.missingVars.length > 5) {
      status = 'critical';
    }

    const message =
      drift.missingVars.length === 0 && drift.extraVars.length === 0
        ? 'No drift detected — .env.example is in sync with code usage.'
        : `Drift detected: ${drift.missingVars.length} missing, ${drift.extraVars.length} unused`;

    return { status, message, details };
  }

  /**
   * Generate an updated .env.example from detected variables.
   */
  generateEnvExample(
    variables: Array<{ name: string; defaultValue?: string; description?: string; required: boolean }>,
  ): string {
    const lines: string[] = ['# Auto-generated by EnvDoctor', '# Generated at: ' + new Date().toISOString(), ''];

    // Required vars first
    const required = variables.filter((v) => v.required);
    const optional = variables.filter((v) => !v.required);

    if (required.length > 0) {
      lines.push('# Required');
      for (const v of required) {
        if (v.description) lines.push(`# ${v.description}`);
        lines.push(`${v.name}=`);
        lines.push('');
      }
    }

    if (optional.length > 0) {
      lines.push('# Optional');
      for (const v of optional) {
        if (v.description) lines.push(`# ${v.description}`);
        lines.push(`${v.name}=${v.defaultValue || ''}`);
        lines.push('');
      }
    }

    return lines.join('\n');
  }
}

export const driftDetector = new DriftDetector();
