import { Hero } from '@/components/hero';
import { FeatureCards } from '@/components/feature-cards';
import { CodeBlock } from '@/components/code-block';

const sampleOutput = `// Auto-generated by EnvDoctor
import { z } from 'zod';

const envSchema = z.object({
  databaseUrl: z.string().url(),
  port: z.coerce.number().default(3000),
  apiKey: z.string(), // 🔒 API_KEY
  debug: z.coerce.boolean().default(false),
});

export type Env = z.infer<typeof envSchema>;

const parsed = envSchema.safeParse(process.env);
if (!parsed.success) {
  console.error('❌ Invalid environment variables:');
  throw new Error('Invalid environment variables');
}

export const env = parsed.data;`;

export default function HomePage() {
  return (
    <>
      <Hero />
      <FeatureCards />

      {/* Code output preview */}
      <section className="container py-20">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tight">
            From this <span className="text-muted-foreground">↓</span>
          </h2>
          <pre className="mt-6 rounded-lg border bg-muted p-4 text-sm font-mono">
{`process.env.DATABASE_URL
process.env.PORT
process.env.API_KEY
process.env.DEBUG`}
          </pre>
          <h2 className="mt-12 text-3xl font-bold tracking-tight">
            To this <span className="text-muted-foreground">↓</span>
          </h2>
          <div className="mt-6 text-left">
            <CodeBlock code={sampleOutput} language="typescript" filename="env.ts" />
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="container pb-20">
        <div className="relative overflow-hidden rounded-2xl border bg-gradient-to-br from-emerald-500/10 via-teal-500/5 to-cyan-500/10 p-12 text-center">
          <h2 className="text-3xl font-bold tracking-tight">
            Ready to audit your environment?
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-muted-foreground">
            Upload your files and get a complete report in seconds. No signup required.
          </p>
          <a
            href="/projects/new"
            className="mt-8 inline-flex h-12 items-center justify-center rounded-md bg-primary px-8 text-base font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Get Started — It's Free
          </a>
        </div>
      </section>
    </>
  );
}
